pluginManagement {
    repositories {
        maven {
            url = uri('https://central.sonatype.com/repository/maven-snapshots/')
            mavenContent {
                snapshotsOnly()
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'laa-ccms-caab-assessment-api'

include 'assessment-api'
include 'assessment-service'
