INSERT INTO XXCCMS_OPA_SESSION (ID, OWNER_ID, TARGET_ID, ASSESSMENT, STATUS, CREATED_BY, MODIFIED_BY)
VALUES (26, 'owner1', '1234567890', 'assessment1', 'status1', 'creator1', 'modifier1');

-- Insert into XXCCMS_OPA_LISTENTITY
INSERT INTO XXCCMS_OPA_LISTENTITY (ID, FK_OPA_SESSION, ENTITY_TYPE)
VALUES (27, 26, 'entityType1');

-- Insert into XXCCMS_OPA_ENTITY
INSERT INTO XXCCMS_OPA_ENTITY (ID, FK_OPA_LIST_ENTITY, FK_OPA_SESSION, ENTITY_ID, PREPOPULATED, COMPLETED)
VALUES (28, 27, 26, 'entityId1', 0, 0);

-- Insert into XXCCMS_OPA_ATTRIBUTE
INSERT INTO XXCCMS_OPA_ATTRIBUTE (ID, FK_OPA_ENTITY, ATTRIBUTE_ID, ATTRIBUTE_TYPE, ATTRIBUTE_VALUE, INFERENCING_TYPE, PREPOPULATED, ASKED)
VALUES (29, 28, 'OPPONENT_DOB', 'text', null, null, 0, 0);

-- Insert into XXCCMS_OPA_RELATIONSHIP
INSERT INTO XXCCMS_OPA_RELATIONSHIP (ID, FK_OPA_ENTITY, NAME, PREPOPULATED)
VALUES (30, 28, 'name1', 1);

-- Insert into XXCCMS_OPA_RELSHIPTARGET
INSERT INTO XXCCMS_OPA_RELSHIPTARGET (ID, TARGET_ENTITY_ID)
VALUES (31, 'entityId1');

INSERT INTO XXCCMS_OPA_CHECKPOINT (RESUME_ID, USER_NAME, INTERVIEW_DATA)
VALUES (26, 'john.doe', hextoraw('48656c6c6f20776f726c64'));


