DROP TABLE XXCCMS_OPA_RELSHIPTARGET;
DROP TABLE XXCCMS_OPA_RELATIONSHIP;
DROP TABLE XXCCMS_OPA_ATTRIBUTE;
DROP TABLE XXCCMS_OPA_ENTITY;
DROP TABLE XXCCMS_OPA_LISTENTITY;
DROP TABLE XXCCMS_OPA_CHECKPOINT;
DROP TABLE XXCCMS_OPA_SESSION;