

CREATE TABLE XXCCMS_PUI.XXCCMS_OPA_SESSION (
    ID NUMBER(19, 0) NOT NULL,
    OWNER_ID VARCHAR2(255 CHAR) NOT NULL,
    TARGET_ID VARCHAR2(255 CHAR) NOT NULL,
    ASSESSMENT VARCHAR2(255 CHAR) NOT NULL,
    STATUS VARCHAR2(20 CHAR),
    CREATED DATE DEFAULT SYSDATE,
    MODIFIED DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_BY VARCHAR2(255 CHAR),
    PRIMARY KEY (ID)
);

CREATE TABLE XXCCMS_PUI.XXCCMS_OPA_LISTENTITY (
    ID NUMBER(19, 0) NOT NULL,
    FK_OPA_SESSION NUMBER(19, 0),
    ENTITY_TYPE VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_OPA_SESSION) REFERENCES XXCCMS_PUI.XXCCMS_OPA_SESSION(ID)
);

CREATE TABLE XXCCMS_PUI.XXCCMS_OPA_ENTITY (
    ID NUMBER(19, 0) NOT NULL,
    FK_OPA_LIST_ENTITY NUMBER(19, 0) NOT NULL,
    FK_OPA_SESSION NUMBER(19, 0) NOT NULL,
    ENTITY_ID VARCHAR2(255 CHAR),
    PREPOPULATED NUMBER(1, 0),
    COMPLETED NUMBER(1, 0),
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_OPA_LIST_ENTITY) REFERENCES XXCCMS_PUI.XXCCMS_OPA_LISTENTITY(ID),
    FOREIGN KEY (FK_OPA_SESSION) REFERENCES XXCCMS_PUI.XXCCMS_OPA_SESSION(ID)
);

CREATE TABLE XXCCMS_PUI.XXCCMS_OPA_ATTRIBUTE (
    ID NUMBER(19, 0) NOT NULL,
    FK_OPA_ENTITY NUMBER(19, 0) NOT NULL,
    ATTRIBUTE_ID VARCHAR2(100 CHAR) NOT NULL,
    ATTRIBUTE_TYPE VARCHAR2(255 CHAR) NOT NULL,
    ATTRIBUTE_VALUE CLOB,
    INFERENCING_TYPE VARCHAR2(255 CHAR),
    PREPOPULATED NUMBER(1, 0) NOT NULL,
    ASKED NUMBER(1, 0),
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_OPA_ENTITY) REFERENCES XXCCMS_PUI.XXCCMS_OPA_ENTITY(ID)
);

CREATE TABLE XXCCMS_PUI.XXCCMS_OPA_RELATIONSHIP (
    ID NUMBER(19, 0) NOT NULL,
    FK_OPA_ENTITY NUMBER(19, 0) NOT NULL,
    NAME VARCHAR2(255 CHAR),
    PREPOPULATED NUMBER(1, 0),
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_OPA_ENTITY) REFERENCES XXCCMS_PUI.XXCCMS_OPA_ENTITY(ID)
);

CREATE TABLE XXCCMS_PUI.XXCCMS_OPA_RELSHIPTARGET (
    ID NUMBER(19, 0) NOT NULL,
    TARGET_ENTITY_ID VARCHAR2(255 CHAR) NOT NULL,
    FK_OPA_RELATIONSHIP NUMBER(19, 0),
    PRIMARY KEY (ID)
);

CREATE TABLE XXCCMS_PUI.XXCCMS_OPA_CHECKPOINT (
    RESUME_ID NUMBER(19,0) NOT NULL,
    USER_NAME VARCHAR2(255 CHAR),
    INTERVIEW_DATA BLOB,
    CONSTRAINT PK_OPA_CHECKPOINT PRIMARY KEY (RESUME_ID)
);

create sequence XXCCMS_PUI.XXCCMS_OPA_GENERATED_ID_S;

CREATE TABLE XXCCMS_PUI.XXCCMS_OPA_ASSESSMENT_LOG (
    ID NUMBER(19,0) NOT NULL,
    TARGET_ID VARCHAR2(360) NOT NULL,
    ASSESSMENT VARCHAR2(36),
    OWNER_ID VARCHAR2(36),
    ACTION VARCHAR2(36),
    TTL VARCHAR2(200),
    ASSESSMENT_DATA CLOB,
    CREATED TIMESTAMP (6) NOT NULL,
    CREATED_BY VARCHAR2(50)
);