DELETE FROM XXCCMS_PUI.XXCCMS_OPA_RELSHIPTARGET;
DELETE FROM XXCCMS_PUI.XXCCMS_OPA_RELATIONSHIP;
DELETE FROM XXCCMS_PUI.XXCCMS_OPA_ATTRIBUTE;
DELETE FROM XXCCMS_PUI.XXCCMS_OPA_ENTITY;
DELETE FROM XXCCMS_PUI.XXCCMS_OPA_LISTENTITY;
DELETE FROM XXCCMS_PUI.XXCCMS_OPA_CHECKPOINT;
DELETE FROM XXCCMS_PUI.XXCCMS_OPA_SESSION;
DELETE FROM XXCCMS_PUI.XXCCMS_OPA_ASSESSMENT_LOG;
