spring:
  application:
    name: laa-ccms-caab-assessment-api
  datasource:
    url: ${CAAB_DATASOURCE_URL}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${CAAB_DATASOURCE_USERNAME}
    password: ${CAAB_DATASOURCE_PASSWORD}
    hikari:
      maxLifeTime: 300000 # 5 minutes - @Todo Needs review
      maximum-pool-size: 10
      minimum-idle: 5
      data-source-properties:
        oracle.jdbc.defaultConnectionValidation: LOCAL
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  threads:
    virtual:
      enabled: true

laa:
  ccms:
    springboot.starter.auth:
      authentication-header: "Authorization"
      authorized-clients: ${AUTHORIZED_CLIENTS}
      authorized-roles: ${AUTHORIZED_ROLES}
      unprotected-uris: ${UNPROTECTED_URIS}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus