#!/bin/sh
# scripts/pre-commit

# Run spotlessApply
changed_java_files=$(git diff --cached --name-only -- 'assessment-service/src/*/java/**/*.java')
if [ -n "$changed_java_files" ]; then
  echo "Running Spotless Apply..."
  ./gradlew spotlessApply

  # Re-add files that were changed by Spotless
  # This ensures that formatting changes are included in the current commit
  git add $(git diff --name-only --cached)
fi
