# This workflow is part of the application's build and deployment pipeline.
# The workflow delegates these activities to reusable workflows maintained in
# https://github.com/ministryofjustice/laa-ccms-common-workflows.

name: Build feature

on:
  push:
    branches-ignore:
      - main
      - 'feature-dev/*'
      - 'feature-test/*'

jobs:
  build-and-publish-snapshot:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v2.4.0
    permissions:
      contents: write
      packages: write
    with:
      java_version: '25'
      java_distribution: 'corretto'
      integration_test_task: "integrationTest --tests '*IntegrationTest'"
      release_type: 'snapshot'
      junit_results_path: 'assessment-service/build/test-results'
      junit_report_path: 'assessment-service/build/reports/tests'
      checkstyle_report_path: 'assessment-service/build/reports/checkstyle'
      jacoco_coverage_report_path: 'assessment-service/build/reports/jacoco'
      semgrep_check: true
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  get-branch-ref:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: meta
        with:
          tags: |
            type=ref,event=branch

  scan-image:
    needs: [ get-branch-ref ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@v2.4.0
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      java_version: '25'
      java_distribution: 'corretto'
      image_version: ${{ format('{0}-{1}', vars.IMAGE_PREFIX, needs.get-branch-ref.outputs.version) }}
      jar_subproject: 'assessment-service'
      publish: false
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
      ecr_region: ${{ vars.ECR_REGION }}
      ecr_role_to_assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      snyk_client_id: ${{ secrets.SNYK_CLIENT_ID }}
      snyk_client_secret: ${{ secrets.SNYK_CLIENT_SECRET }}
