name: Deploy main

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        default: "auto"
        options: [ "auto", "none", "patch", "minor", "major" ]

permissions:
  contents: read

jobs:
  build-and-publish-release:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v2
    permissions:
      contents: write
      packages: write
    with:
      java_version: '25'
      java_distribution: 'corretto'
      integration_test_task: "integrationTest --tests '*IntegrationTest'"
      release_type: ${{ inputs.release_type != 'auto' && inputs.release_type || '' }}
      junit_results_path: 'assessment-service/build/test-results'
      junit_report_path: 'assessment-service/build/reports/tests'
      checkstyle_report_path: 'assessment-service/build/reports/checkstyle'
      jacoco_coverage_report_path: 'assessment-service/build/reports/jacoco'
      github_bot_username: 'laa-ccms-caab-service'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      github_app_id: ${{ vars.LAA_CCMS_CAAB_SERVICE_APP_ID }}
      github_app_private_key: ${{ secrets.LAA_CCMS_CAAB_SERVICE_KEY }}
      github_app_organisation: 'ministryofjustice'

  ecr-publish-image:
    needs: [ build-and-publish-release ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@v2
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      java_version: '25'
      java_distribution: 'corretto'
      image_version: ${{ format('{0}-{1}', vars.IMAGE_PREFIX, needs.build-and-publish-release.outputs.published_artifact_version) }}
      jar_subproject: 'assessment-service'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
      ecr_region: ${{ vars.ECR_REGION }}
      ecr_role_to_assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      snyk_client_id: ${{ secrets.SNYK_CLIENT_ID }}
      snyk_client_secret: ${{ secrets.SNYK_CLIENT_SECRET }}

  update-helm-chart:
    needs: [ ecr-publish-image ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/update-helm-chart.yml@v2
    with:
      helm_charts_repository: 'laa-ccms-caab-helm-charts'
      helm_charts_branch: 'development'
      service_name: 'laa-ccms-caab-service'
      subchart_name: 'caab-assessment-api'
      application_version: ${{ needs.ecr-publish-image.outputs.published_image_version }}
      github_bot_username: 'laa-ccms-caab-service'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      github_app_id: ${{ vars.LAA_CCMS_CAAB_SERVICE_APP_ID }}
      github_app_private_key: ${{ secrets.LAA_CCMS_CAAB_SERVICE_KEY }}
      github_app_organisation: 'ministryofjustice'
