name: CI feature branch and deploy

on:
  push:
    branches:
      - 'feature-dev/**'
      - 'feature-test/**'

permissions:
  contents: read

jobs:
  set-short-repo-name:
    runs-on: ubuntu-latest
    steps:
      - uses: ministryofjustice/laa-ccms-common-workflows/.github/actions/remove-prefix@story/ccmspui-35-common-workflows
        with:
          string: ${{ github.event.repository.name }}
          prefix: '*laa-ccms-'

  set-version-override:
    runs-on: ubuntu-latest
    outputs:
      feature_version: ${{ steps.get-feature-version.outputs.feature_version }}
    steps:
      - uses: ministryofjustice/laa-ccms-common-workflows/.github/actions/remove-prefix@story/ccmspui-35-common-workflows
        id: get-feature-name
        with:
          string: ${{ github.ref_name }}
          prefix: 'feature-*/'
      - name: Get feature version
        id: get-feature-version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "feature_version=${{ steps.get-feature-name.outputs.result }}-${COMMIT_HASH}-SNAPSHOT" >> $GITHUB_OUTPUT
          echo "Feature version: ${{ steps.get-feature-name.outputs.result }}-${COMMIT_HASH}-SNAPSHOT"

  build-test-publish:
    needs: [ set-version-override ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@story/ccmspui-35-common-workflows
    permissions:
      contents: read
      packages: write
    with:
      java_version: 21
      java_distribution: 'temurin'
      integration_test_task: "integrationTest --tests '*IntegrationTest'"
      publish_package: 'true'
      override_version: ${{ needs.set-version-override.outputs.feature_version }}
      junit_results_path: 'assessment-service/build/test-results'
      junit_report_path: 'assessment-service/build/reports/tests'
      checkstyle_report_path: 'assessment-service/build/reports/checkstyle'
      jacoco_coverage_report_path: 'assessment-service/build/reports/jacoco'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  ecr-publish-image:
    needs: [ set-short-repo-name, build-test-publish ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@story/ccmspui-35-common-workflows
    permissions:
      contents: read
      id-token: write
    with:
      java_version: 21
      java_distribution: 'temurin'
      image_version: ${{ needs.set-short-repo-name.outputs.result }}-${{ needs.assemble-and-publish-snapshot.outputs.pubished_artifact_version }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
      ecr_region: ${{ vars.ECR_REGION }}
      ecr_role_to_assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  update-helm-chart:
    needs: [ ecr-publish-image ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/update-helm-chart.yml@story/ccmspui-35-common-workflows
    with:
      helm_charts_repository: 'laa-ccms-caab-helm-charts'
      helm_charts_branch: 'development'
      service_name: 'laa-ccms-caab-service'
      subchart_name: 'caab-assessment-api'
      application_version: ${{ needs.ecr-publish-image.outputs.published_image_version }}
      feature_branch: ${{ github.ref_name }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}