name: Lint PR title

on:
  pull_request:
    branches: [ main ]
    types: [ opened, edited, synchronize, reopened ]

jobs:
  lint-pr-title:
    permissions:
      pull-requests: read
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/lint-pr-title.yml@0c06c747af49e3efb703717e6185cf693494d5a4 # v2.4.2
