name: Lint PR title

on:
  pull_request:
    branches: [ main ]
    types: [ opened, edited, synchronize, reopened ]

jobs:
  lint-pr-title:
    permissions:
      pull-requests: read
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/lint-pr-title.yml@406b0059a52f3d906b102f2f9cde2a5ce1337382 # v2.4.1
