# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: main

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: read

jobs:
  build-and-publish-release:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@story/ccmspui-35-common-workflows
    permissions:
      packages: write
    with:
      java_version: 21
      java_distribution: 'temurin'
      integration_test_task: "integrationTest --tests '*IntegrationTest'"
      create_tag: 'true'
      junit_results_path: 'assessment-service/build/test-results'
      junit_report_path: 'assessment-service/build/reports/tests'
      checkstyle_report_path: 'assessment-service/build/reports/checkstyle'
      jacoco_coverage_report_path: 'assessment-service/build/reports/jacoco'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  vulnerability-report:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/snyk-vulnerability-report.yml@story/ccmspui-35-common-workflows
    permissions:
      security-events: write
    with:
      java_version: 21
      java_distribution: 'temurin'
      snyk_organisation: 'legal-aid-agency'
      snyk_test_exclude: 'build,generated'
      snyk_target_reference: 'main'
      github_code_scanning_report: 'true'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      snyk_token: ${{ secrets.SNYK_TOKEN }}
