name: build feature branch

on:
  push:
    branches-ignore:
      - main
      - 'feature-dev/*'
      - 'feature-test/*'

permissions:
  contents: read
  packages: write

jobs:

  build-test:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-test.yml@story/ccmspui-35-common-workflows
    with:
      java_version: 21
      java_distribution: 'temurin'
      integration_test_task: "integrationTest --tests '*IntegrationTest'"
      update_snapshot: 'false'
      publish_package: 'false'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  vulnerability-scan:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/snyk-vulnerability-scan.yml@story/ccmspui-35-common-workflows
    with:
      java_version: 21
      java_distribution: 'temurin'
      snyk_organisation: 'legal-aid-agency'
      snyk_test_exclude: 'build,generated'
      snyk_target_reference: 'main'
    secrets:
      gh_token: ${{ secrets.gh_token }}
      snyk_token: ${{ secrets.snyk_token }}
