name: assessment-api pipeline

on:
  push:
    branches-ignore:
      - main
      - 'feature-dev/*'
      - 'feature-test/*'

permissions:
  contents: read
  packages: write

jobs:
  build-test-publish:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-test.yml@story/ccmspui-35-common-workflows
    with:
      java_version: 21
      java_distribution: 'temurin'
      integration_test_task: |
        integrationTest --tests '*IntegrationTest'
      snyk_vulnerability_scan: 'true'
      snyk_organisation: 'legal-aid-agency'
      snyk_test_exclude: 'build,generated'
      snyk_target_reference: 'main'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      snyk_token: ${{ secrets.SNYK_TOKEN }}
